from AI_COVID19.init import *

path_title = {'local': ['p200825', 't200825'],
              'server': ['p200901', 't200915'],
              'test': 'r200730',
              'tests': 'r200731'}

path_param_set = {'local': {'input_path': {'dataset': 'E:\\Dataset\\COVID19\\Covid_pneumonia',
                                           'prep': 'E:\\Dataset\\COVID19\\%s\\org' % path_title['local'][0],
                                           'train': 'E:\\Dataset\\COVID19\\%s\\prep' % path_title['local'][0]},
                             'output_path': {'log': 'E:\\Dataset\\COVID19\\log',
                                             'prep': 'E:\\Dataset\\COVID19\\%s' % path_title['local'][0],
                                             'train': 'E:\\Dataset\\COVID19\\%s' % path_title['local'][1]}},
                  'server': {'input_path': {'dataset': '/data/jjh/MedicalDataset/COVID19/Covid_pneumonia',
                                            'prep': '/data/jjh/MedicalDataset/COVID19/%s/org' % path_title['server'][0],
                                            'train': '/data/jjh/MedicalDataset/COVID19/%s/prep' % path_title['server'][0]},
                             'output_path': {'log': '/data/jjh/MedicalDataset/COVID19/log',
                                             'prep': '/data/jjh/MedicalDataset/COVID19/%s' % path_title['server'][0],
                                             'train': '/data/jjh/MedicalDataset/COVID19/%s' % path_title['server'][1]}}}


prep_param_set = {'npz_convert': {'class_type': '4cls',
                                  'data_limit': None,
                                  'fig_mode': ['png'],
                                  'fig_sample': 1},
                  'pre_process': {'data_mode': 'train',
                                  'data_limit': None,
                                  'step_list': [1,2,3,4,5],
                                  'Resize_param': {'size': [256, 256], 'mode': '2d'},
                                  'Adap_param': {'clip': 0.01},
                                  'fig_mode': ['png'],
                                  'fig_sample': 0.1}}

train_param_set = {'cls_vgg': {'train_mode': 'train',
                               'data_limit': None,
                               'model_name': 'VGG19',
                               'step_list': [1,2,3,4,5],
                               'gpu_vision': '3,4,6',
                               'datagen': kimg.ImageDataGenerator(rotation_range=20,
                                                                  width_shift_range=0.1,
                                                                  height_shift_range=0.1,
                                                                  shear_range=0.1,
                                                                  zoom_range=0.1,
                                                                  horizontal_flip=True,
                                                                  vertical_flip=False,
                                                                  fill_mode='nearest'),
                               'Step1_param': {'class_mode': '3cls',
                                               'split_mode': 'num',
                                               'split_rate': {'test': 50,
                                                              'val': 100,
                                                              'fold_num': 5,
                                                              'fold_range': [0,1]}},
                               'Step2_param': {'aug_rate': {'Covid19': 8, 'Bacterial': 1, 'Viral': 3, 'Pneumonia': 1, 'Normal': 3},
                                               'fig_mode': 'png',
                                               'fig_sample': 0.1},
                               'Step3_param': {'array_dim': '2d',
                                               'loss': losses.CategoricalCrossentropy(),
                                               'learning_rate': '1e-4',
                                               'optimizer': optimizers.Adam(lr=1e-4),
                                               'metric': ['accuracy']},
                               'Step4_param': {'batch': 32,
                                               'epoch': 100},
                               'Step5_param': {'pos_id1': {'name': 'Covid19',
                                                          'idx': 0},
                                               'pos_id2': {'name': 'Pneumonia',
                                                           'idx': 1}},
                               'ensemble_mode': 'soft'},
                   'cls_res': {'train_mode': 'train',
                               'data_limit': None,
                               'model_name': 'ResNet152',
                               'step_list': [1,2,3,5],
                               'gpu_vision': '3,4,6',
                               'datagen': kimg.ImageDataGenerator(rotation_range=20,
                                                                  width_shift_range=0.1,
                                                                  height_shift_range=0.1,
                                                                  shear_range=0.1,
                                                                  zoom_range=0.1,
                                                                  horizontal_flip=True,
                                                                  vertical_flip=False,
                                                                  fill_mode='nearest'),
                               'Step1_param': {'class_mode': '3cls',
                                               'split_mode': 'num',
                                               'split_rate': {'test': 50,
                                                              'val': 100,
                                                              'fold_num': 5,
                                                              'fold_range': [0, 1]}},
                               'Step2_param': {'aug_rate': {'Covid19': 1, 'Bacterial': 1, 'Viral': 3, 'Pneumonia': 1, 'Normal': 1}, # (8,1,3,1,3)
                                               'fig_mode': 'png',
                                               'fig_sample': 0.1},
                               'Step3_param': {'array_dim': '2d',
                                               'loss': losses.CategoricalCrossentropy(),
                                               'learning_rate': '1e-4',
                                               'optimizer': optimizers.Adam(lr=1e-4),
                                               'metric': ['accuracy']},
                               'Step4_param': {'batch': 32,
                                               'epoch': 100},
                               'Step5_param': {'pos_id1': {'name': 'Covid19',
                                                          'idx': 0},
                                               'pos_id2': {'name': 'Pneumonia',
                                                           'idx': 1}},
                               'ensemble_mode': 'soft'}}

network_param_set = {'vgg': {'input_size': 256,
                             'block_num': 1,
                             'layer_num': 1,
                             'drop_out': 0.5,
                             'reg_val': '1e-4',
                             'conv_reg_weight': None,
                             'dens_reg_weight': regularizers.l1_l2(1e-4),
                             'dens_num': 2,
                             'dens_count': [1000, 500],
                             'output_count': 3,
                             'conv_act': 'relu',
                             'dens_act': 'relu',
                             'output_act': 'softmax',
                             'conv_str': 3,
                             'pool_str': 2},
                     'resnet': {'input_size': 256,
                                'channel_num': 1,
                                'reg_val': 'conv/dens : 1e-5/1e-4',
                                'conv_reg_weight': regularizers.l1_l2(1e-5),
                                'dens_reg_weight': regularizers.l1_l2(1e-4),
                                'act_func': 'relu',
                                'dens_num': 3,
                                'dens_count': [1024, 512, 256],
                                'drop_rate': 0.5,
                                'output_count': 3,
                                'output_act': 'softmax'}}